services:
    db:
      image: mysql
      container_name: db
      environment:
        MYSQL_ROOT_PASSWORD: R00t_123@
        MYSQL_DATABASE: HackerMaster
        MYSQL_USER: hackermaster
        MYSQL_PASSWORD: Hm_123@
      volumes:
        - ./sources/datos_mysql:/var/lib/mysql
      networks:
        red_backend:
          ipv4_address: 192.168.1.3
    
    backend:
      image: node
      container_name: backend
      volumes:
        - ./sources/backend:/app
        - /var/run/docker.sock:/var/run/docker.sock
      depends_on:
        - db
      networks:
        red_backend:
          ipv4_address: 192.168.1.2
        red_frontend:
          ipv4_address: 192.168.2.2
        red_maquinas:
          ipv4_address: 192.168.3.2
      env_file:
        - ./sources/backend/.env
      command: ["/bin/bash", "-c", "curl -o /usr/local/bin/wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh && chmod +x /usr/local/bin/wait-for-it.sh && /usr/local/bin/wait-for-it.sh 192.168.1.3:3306 --timeout=60 -- node --watch /app/server.js"]
    
    frontend:
      image: sergiogn04/angular
      container_name: frontend
      volumes:
        - ./sources/frontend:/app
      depends_on:
        - backend
      networks:
        red_frontend:
          ipv4_address: 192.168.2.3
      working_dir: /app
      command: ["ng","serve","--host","0.0.0.0"]
      ports:
        - "4200:4200"

networks:
  red_backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24

  red_frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
  
  red_maquinas:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.3.0/24